version: '3.8'

services:
  memsther:
    image: ghcr.io/lpoto/memsther:latest
    #build:
      #context: ./
      #dockerfile: ./Dockerfile
    environment:
      RUST_LOG: "warn,memsther=info"
      DISCORD_TOKEN: <discord-bot-token>
      GIPHY_KEY: <giphy-api-key>
      POSTGRES_DB: memsther
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - memsther
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5433:5432
    environment:
        POSTGRES_DB: memsther
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      - memsther

networks:
  memsther:
volumes:
  postgres_data:
