# Publish docker image lpoto/memsther:latest
# to ghcr.io
name: Publish Latest Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image with tag 'latest' to Docker Hub
    # make sure the tests were successful
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/memsther:latest

